/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as SkillRouteImport } from './routes/skill'
import { Route as ScriptRouteImport } from './routes/script'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ElementsRouteImport } from './routes/elements'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsTeamRouteImport } from './routes/settings/team'
import { Route as SettingsRedeemRouteImport } from './routes/settings/redeem'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillRoute = SkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptRoute = ScriptRouteImport.update({
  id: '/script',
  path: '/script',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementsRoute = ElementsRouteImport.update({
  id: '/elements',
  path: '/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRedeemRoute = SettingsRedeemRouteImport.update({
  id: '/settings/redeem',
  path: '/settings/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/elements': typeof ElementsRoute
  '/projects': typeof ProjectsRoute
  '/quick': typeof QuickRoute
  '/script': typeof ScriptRoute
  '/skill': typeof SkillRoute
  '/tutorial': typeof TutorialRoute
  '/tv': typeof TvRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/redeem': typeof SettingsRedeemRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/elements': typeof ElementsRoute
  '/projects': typeof ProjectsRoute
  '/quick': typeof QuickRoute
  '/script': typeof ScriptRoute
  '/skill': typeof SkillRoute
  '/tutorial': typeof TutorialRoute
  '/tv': typeof TvRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/redeem': typeof SettingsRedeemRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/elements': typeof ElementsRoute
  '/projects': typeof ProjectsRoute
  '/quick': typeof QuickRoute
  '/script': typeof ScriptRoute
  '/skill': typeof SkillRoute
  '/tutorial': typeof TutorialRoute
  '/tv': typeof TvRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/redeem': typeof SettingsRedeemRoute
  '/settings/team': typeof SettingsTeamRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/elements'
    | '/projects'
    | '/quick'
    | '/script'
    | '/skill'
    | '/tutorial'
    | '/tv'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/redeem'
    | '/settings/team'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/elements'
    | '/projects'
    | '/quick'
    | '/script'
    | '/skill'
    | '/tutorial'
    | '/tv'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/redeem'
    | '/settings/team'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/elements'
    | '/projects'
    | '/quick'
    | '/script'
    | '/skill'
    | '/tutorial'
    | '/tv'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/profile'
    | '/settings/redeem'
    | '/settings/team'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ElementsRoute: typeof ElementsRoute
  ProjectsRoute: typeof ProjectsRoute
  QuickRoute: typeof QuickRoute
  ScriptRoute: typeof ScriptRoute
  SkillRoute: typeof SkillRoute
  TutorialRoute: typeof TutorialRoute
  TvRoute: typeof TvRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsRedeemRoute: typeof SettingsRedeemRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill': {
      id: '/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof SkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/script': {
      id: '/script'
      path: '/script'
      fullPath: '/script'
      preLoaderRoute: typeof ScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elements': {
      id: '/elements'
      path: '/elements'
      fullPath: '/elements'
      preLoaderRoute: typeof ElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/redeem': {
      id: '/settings/redeem'
      path: '/settings/redeem'
      fullPath: '/settings/redeem'
      preLoaderRoute: typeof SettingsRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ElementsRoute: ElementsRoute,
  ProjectsRoute: ProjectsRoute,
  QuickRoute: QuickRoute,
  ScriptRoute: ScriptRoute,
  SkillRoute: SkillRoute,
  TutorialRoute: TutorialRoute,
  TvRoute: TvRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsRedeemRoute: SettingsRedeemRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
